sudo: false
language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

install: 
  - mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V

notifications:
  email: false

# whitelist
branches:
  only:
    - dev
